service: serverless-office-to-pdf-2

provider:
  name: aws
  runtime: nodejs14.x
  region: eu-west-2
  memorySize: 2048
  timeout: 30
  stage: dev
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:*
          Resource: 'arn:aws:s3:::${self:custom.s3BucketName}/*'
  environment:
    S3_BUCKET_NAME: ${self:custom.s3BucketName}

plugins:
 - serverless-esbuild
 - serverless-offline

custom:
  serverlessPluginTypescript:
    tsConfigFileLocation: './tsconfig.build.json'
  s3BucketName: ${self:service}-${self:provider.stage}-assets

functions:
  index:
    handler: src/index.handler
    layers: 
      - arn:aws:lambda:eu-west-2:764866452798:layer:libreoffice-brotli:1
    events:
      - http:
          path: '/'
          method: any
      - http:
          path: '{proxy+}'
          method: any

resources:
  Resources:
    UserAssets:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.s3BucketName}
        CorsConfiguration:
          CorsRules:
          - AllowedHeaders:
              - "*"
            AllowedMethods:
              - GET
              - PUT
              - HEAD
            AllowedOrigins:
              - "*"
        LifecycleConfiguration:
          Rules:
            - ExpirationInDays: 30
              Prefix: '/'
              Status: Enabled
