service: serverless-express-recaptcha

provider:
  name: aws
  runtime: nodejs14.x
  region: eu-west-3
  environment:
    RECAPTCHA_VERIFY_URL: 'https://www.google.com/recaptcha/api/siteverify'
    RECAPTCHA_SECRET: '<your_recaptcha_secret>'

plugins:
 - serverless-esbuild
 - serverless-offline

custom:
  serverlessPluginTypescript:
    tsConfigFileLocation: './tsconfig.build.json'

functions:
  index:
    handler: src/index.handler
    events:
      - http:
          path: '/'
          method: any
          cors:
            origin: '*'
            headers: '*'
            allowCredentials: false
      - http:
          path: '{proxy+}'
          method: any
          cors:
            origin: '*'
            headers: '*'
            allowCredentials: false
